name: auth-checking

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run auth tests
        run: cd auth && npm install && npm run test:ci

     
