name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
      - run: doctl auth init -t "dop_v1_4e1dfa7550e84fe39942415636f6e1b90a69fab80e9973a5a2355b202d37e8c5"
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
