name: payments-checking

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run payments tests
        run: cd payments && npm install && npm run test:ci
